### ISSUE TITLE
Potential UB

### ISSUE THREAD

**Issue by 197g** [oberien/str-concat#3]
The docs for `slice::from_raw_parts` state:

> The total size of the slice must be no larger than isize::MAX bytes in memory. See the safety documentation of pointer::offset.

Since the internal representation is a *byte* slice, this is equivalent to the `len` being smaller than this limit. However, this crate [only checks](https://github.com/oberien/str-concat/blob/bf6c26041714532b33586b460ce4045978fc1826/src/lib.rs#L45) that the length of `a` is smaller than this limit, not the sum of both strings. This is redundant (because `a.len()` is already guaranteed to be smaller than `isize::max_value()` as it comes from a slice) and not enough to guarantee that `a.len() + b.len()` conforms to the requirements for totally avoiding UB.

So, I'm about to fix this. ~~Can I factor out `concat_slice` in a `pub fn` in the same PR? It is a part of `concat` right now but would be useful on its own.~~ I'll factor out the byte concatentation into a private `fn` and provide arbitrary typed slice concatentation in a separate PR.

**Comment by oberien** [comment]
Regarding adding `concat_slice`, if we find more types which could use in-memory concatenation, we could think about making `concat` generic over some `T` of a trait, where the trait implements the concatenation. That could allow calling `concat` with any concatenatable thing.

**Comment by 197g** [comment]
I mean (only) literally concatenating `[T]` to `[T]` which is always safe to do with the provided adjacency checks. The special implementation for `str` assures reassembling it from the contained `[u8]` (well not actually contained since, for legacy reasons, `str` will remain a `#[lang_item]` for a while but conceptually contained) slices does not violate the invariants of `str`. The slice type `[T]` has no internal invariants of its own and should always be safe to concatenate in that manner.
